// Generated by LiveScript 1.3.1
var assert, r;
assert = require('assert');
r = require('../src/random');
var types = require('../src/rule');
describe('zeroes all the way on randomRule', function(){
  var x$;
  x$ = it;
  x$('should give me the all red rule', function(){
    var zeroRand, rule;
    zeroRand = {
      next: function(){
        return 0;
      }
    };
    rule = r.randomRule(0, zeroRand);
    assert(rule.equals(types.Rule.All(types.Property.Color(types.Color.red))));
  });
  return x$;
});
describe('twos all the way on randomKoan', function() {
  it('should give 3H 3H', function() {
    var twoRand = { next: function() { return 2; } };
    koan = r.randomKoan(twoRand);
    assert.deepEqual(koan, ['3H','3H']);
  });
});
