// Generated by LiveScript 1.3.1
var randomRule, randomProperty, randomColor, randomSuit, randomRank;
var types = require('./rule');
var defaultRand = {
  next: function(cap){
    return Math.floor(Math.random() * cap);
  }
};
randomRule = function(complexity, rand){
  if (rand === void 8) {
    rand = defaultRand;
  }
  if (complexity > 0 && rand.next(2) === 0) { return types.Rule.And(randomRule(complexity - 1, rand), randomRule(complexity - 1, rand));
  } else if (rand.next(2) === 0) {
    return types.Rule.All(randomProperty(complexity, rand));
  } else {
    return types.Rule.AtLeastOne(randomProperty(complexity, rand));
  }
};
randomProperty = function(complexity, rand){
  var which;
  which = rand.next(3);
  if (which === 0) {
    return types.Property.Color(randomColor(complexity, rand));
  } else if (which === 1) {
    return types.Property.Rank(randomRank(complexity, rand));
  } else {
    return types.Property.Suit(randomSuit(complexity, rand));
  }
};
randomColor = function(complexity, rand){
  if (rand.next(2) === 0) {
    return types.Color.red;
  } else {
    return types.Color.black;
  }
};
randomSuit = function(complexity, rand){
  var suit;
  suit = rand.next(4);
  var suits = [types.Suit.club, types.Suit.diamond, types.Suit.heart, types.Suit.spade];
  return suits[suit];
};
randomRank = function(complexity, rand){
  var rank;
  rank = rand.next(13);
  var ranks = [
    types.Rank.ace,
    types.Rank.two,
    types.Rank.three,
    types.Rank.four,
    types.Rank.five,
    types.Rank.six,
    types.Rank.seven,
    types.Rank.eight,
    types.Rank.nine,
    types.Rank.ten,
    types.Rank.jack,
    types.Rank.queen,
    types.Rank.king];
  return ranks[rank];
};
var randomKoan = function(rand) {
  if (rand === void 8) {
    rand = defaultRand;
  }
  var size = rand.next(4);
  cards = [];
  for (var j$ = 0; j$ < size; ++j$) {
    var y = j$;
    cards.push("A23456789TJQK"[rand.next(13)] + "CDHS"[rand.next(4)]);
  }
  return cards;
};
module.exports = {
  randomRule: randomRule,
  randomKoan: randomKoan,
  defaultRand: defaultRand
};
